import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'

type SupportedLocale = 'en' | 'nl'

type Translations = Record<string, string>

const en: Translations = {
  'nav.dashboard': 'Dashboard',
  'nav.myDashboard': 'My Dashboard',
  'nav.settings': 'Settings',
  'nav.groups': 'Groups',
  'nav.members': 'Members',
  'nav.payments': 'Payments',
  'nav.payouts': 'Payouts',
  'nav.paymentsDue': 'Payments Due',
  'nav.analytics': 'Analytics',
  'nav.messages': 'Messages',
  'nav.paymentLogs': 'Payment Logs',
  'nav.userManagement': 'User Management',
  'nav.loginLogs': 'Login Logs',
  'auth.login': 'Login',
  'auth.signup': 'Sign up',
  'settings.pageTitle': 'Settings',
  'settings.pageSubtitle': 'Manage your account preferences and app settings',
  'settings.savePreferences': 'Save Preferences',
  'settings.editProfile': 'Edit Profile',
  'settings.cancel': 'Cancel',
  'settings.saveChanges': 'Save Changes',
  'settings.tabs.profile': 'Profile',
  'settings.tabs.notifications': 'Notifications',
  'settings.tabs.security': 'Security',
  'settings.tabs.appearance': 'Appearance',
  'settings.tabs.language': 'Language',
  'settings.tabs.data': 'Data & Export',
  'settings.tabs.banks': 'Banks',
  'settings.tabs.performance': 'Performance',
  'appearance.title': 'Appearance Settings',
  'appearance.theme': 'Theme',
  'appearance.choose': 'Choose your preferred color scheme',
  'language.title': 'Language Settings',
  'language.choose': 'Choose your preferred language for the application',
  'language.english': 'English',
  'language.dutch': 'Nederlands',
  'footer.rights': 'All Rights Reserved',
  'footer.email': 'Email',
  'dashboard.title': 'Dashboard',
  'dashboard.subtitle': 'Overview of your Kasmoni groups and payments',
  'dashboard.addPayment': 'Add Payment',
  'dashboard.createGroup': 'Create Group',
  'dashboard.welcome': 'Welcome to Sranan Kasmoni',
  'dashboard.getStarted': "Your dashboard is ready but there's no data yet. Get started by:",
  'dashboard.createYourFirstGroup': 'Create Your First Group',
  'dashboard.addYourFirstPayment': 'Add Your First Payment',
  'dashboard.noActiveGroups': 'No active groups',
  'dashboard.recentActivity': 'Recent Activity',
  'dashboard.recentPayments': 'Recent Payments',
  'dashboard.recentMembers': 'Recent Members',
  'dashboard.recentGroups': 'Recent Groups',
  'dashboard.noRecentPayments': 'No recent payments',
  'dashboard.noRecentMembers': 'No recent members',
  'dashboard.noRecentGroups': 'No recent groups',
  'dashboard.stats.totalExpected': 'Total Amount Expected',
  'dashboard.stats.totalPaid': 'Total Amount Paid',
  'dashboard.stats.totalReceived': 'Total Amount Received',
  'dashboard.stats.pendingPayments': 'Pending Payments',
  'dashboard.stats.totalDue': 'Total Amount Due',
  'dashboard.stats.overduePayments': 'Overdue Payments',
  'dashboard.stats.totalPayouts': 'Total Payouts',
  'dashboard.stats.activeGroups': 'Active Groups',
  'dashboard.stats.activeMembers': 'Active Members',
  'dashboard.groups.all': 'All Groups',
  'dashboard.groups.headers.name': 'Group Name',
  'dashboard.groups.headers.monthlyAmount': 'Monthly Amount',
  'dashboard.groups.headers.nextRecipient': 'Next Recipient',
  'dashboard.groups.headers.slots': 'Slots',
  'dashboard.groups.headers.slotsProgress': 'Slots Progress',
  'dashboard.groups.headers.last': 'Last',
  'dashboard.groups.headers.created': 'Created',
  'common.refreshingData': 'Refreshing data...',
  'common.tryAgain': 'Try Again',
  'common.testDatabase': 'Test Database',
  'common.loading': 'Loading...',
  'common.viewDetails': 'View Details',
  'common.cards': 'Cards',
  'common.table': 'Table',
  'groups.title': 'Groups',
  'groups.manageSubtitle': 'Manage your savings groups',
  'groups.viewSubtitle': 'View your savings groups',
  'groups.downloadSample': 'Download Sample CSV',
  'groups.exportGroups': 'Export Groups',
  'groups.importCsv': 'Import CSV',
  'groups.createNew': 'Create New Group',
  'groups.loading': 'Loading groups...',
  'groups.noGroupsTitle': 'No Groups Yet',
  'groups.noGroupsAdmin': 'Create your first savings group to get started',
  'groups.noGroupsUser': 'No groups are available yet',
  'groups.activeSection': 'Active Groups',
  'groups.upcomingSection': 'Upcoming Groups',
  'groups.closedSection': 'Closed Groups',
  'groups.sectionCountOne': '{count} group',
  'groups.sectionCountMany': '{count} groups',
  'groups.exportPdf': 'Export PDF',
  'groups.exportingPdf': 'Exporting...',
  'groups.exportPdfError': 'Failed to export PDF. Please try again.',
  'myDashboard.title': 'My Dashboard',
  'myDashboard.subtitle': "Welcome back, {name}! Here's your personal overview",
  'myDashboard.refreshing': 'Refreshing...',
  'myDashboard.refreshData': 'Refresh Data',
  'myDashboard.slotsOverview': 'My Slots Overview',
  'myDashboard.noSlotsTitle': 'No Slots Found',
  'myDashboard.noSlotsDesc': "You don't have any assigned slots yet. Contact your group administrator to get started.",
  'myDashboard.recentActivity': 'Recent Activity',

  // Landing page
  'landing.hero.titleLine1': 'Kasmoni',
  'landing.hero.titleLine2': 'Build Wealth. Build Trust. Together.',
  'landing.hero.subtitle': 'Join the trusted community savings platform that brings people together to achieve financial goals through mutual support and transparency.',
  'landing.hero.getStarted': 'Get Started Today',
  'landing.hero.exploreGroups': 'Explore Groups',
  'landing.stats.activeGroups': 'Active Groups',
  'landing.stats.communityMembers': 'Community Members',
  'landing.stats.totalSavings': 'Total Savings',
  'landing.stats.roundsCompleted': 'Rounds Completed',
  'landing.how.title': 'How Kasmoni Works',
  'landing.how.subtitle': 'A simple, transparent system that empowers communities to save together',
  'landing.how.step1.title': 'Join a Group',
  'landing.how.step1.desc': 'Find a savings group that fits your schedule and contribution amount, starting from SRD 1,000.',
  'landing.how.step2.title': 'Save Regularly',
  'landing.how.step2.desc': 'Make your monthly contributions on time. Everyone contributes the same amount each month.',
  'landing.how.step3.title': 'Receive Your Turn',
  'landing.how.step3.desc': "When it's your turn, receive the full pot - all contributions from your group members.",
  'landing.how.step4.title': 'Build Trust',
  'landing.how.step4.desc': 'Continue saving and supporting others, building lasting relationships and financial security.',
  'landing.why.title': 'Why Choose Sranan Kasmoni?',
  'landing.why.item1.title': 'No Banks, No Credit Checks',
  'landing.why.item1.desc': 'Just real people helping real people with transparent, community-based savings.',
  'landing.why.item2.title': 'Secure & Transparent',
  'landing.why.item2.desc': 'Every transaction is recorded and visible to all group members for complete transparency.',
  'landing.why.item3.title': 'Flexible & Accessible',
  'landing.why.item3.desc': 'Choose your contribution amount and join groups that fit your financial situation.',
  'landing.why.item4.title': 'Community Support',
  'landing.why.item4.desc': 'Build lasting relationships while achieving your financial goals together.',
  'landing.cta.title': 'Ready to Start Your Financial Journey?',
  'landing.cta.subtitle': 'Join thousands of Surinamese who are already building wealth and trust together.',
  'landing.cta.primary': 'Start Saving Today',
  'landing.cta.secondary': 'Browse Groups',
  'landing.contact.title': 'Get in Touch',
  'landing.contact.email': 'Email',
  'landing.contact.followUs': 'Follow Us',
  'landing.contact.facebook': 'Facebook',
  'landing.contact.twitter': 'Twitter',
  'landing.contact.message': 'Have questions about joining a Kasmoni group? Our team is here to help you get started on your community savings journey.',

  // Payments page
  'payments.title': 'Payments',
  'payments.subtitle.admin': 'Track all payments and their status',
  'payments.subtitle.user': 'Track your payments and their status',
  'payments.userNotice': 'Viewing only your payment records',
  'payments.recordPayment': 'Record Payment',
  'payments.summary.totalPaid': 'Total Paid',
  'payments.summary.received': 'Received',
  'payments.summary.pending': 'Pending',
  'payments.summary.notPaid': 'Not Paid',
  'payments.summary.settled': 'Settled',
  'payments.summary.count': '{count} payments',
  'payments.pagination.rowsPerPage': 'Rows per page:',
  'payments.pagination.showing': 'Showing {from}-{to} of {total} payments',
  'payments.pagination.pageOf': 'Page {page} of {pages}',
  'payments.loading': 'Loading payments...',
  'payments.section.all': 'All Payments',
  'payments.section.yours': 'Your Payments',
  'payments.privacy.title': 'Privacy Notice:',
  'payments.privacy.body': 'You are only viewing your own payment records. Administrators can see all payments across the system.',
  'payments.empty.title': 'No Payments Found',
  'payments.empty.desc.admin': 'No payments match your current filters. Try adjusting your search criteria or record your first payment.',
  'payments.empty.desc.user': "You don't have any payments yet.",

  // Members page
  'members.title': 'Members',
  'members.subtitle.admin': "Manage your organization's members",
  'members.subtitle.user': 'View your member information',
  'members.loading': 'Loading members...',
  'members.downloadSample': 'Download Sample CSV',
  'members.importCsv': 'Import CSV',
  'members.addMember': 'Add Member',
  'members.viewMode': 'View Mode:',
  'members.cards': 'Cards',
  'members.table': 'Table',
  'members.csvResults': 'CSV Import Results',
  'members.importErrors': 'Import Errors:',
  'members.searchPlaceholder': 'Search members by name, national ID, phone, bank, or account number...',
  'members.filter.allCities': 'All Cities',
  'members.sort.by': 'Sort by:',
  'members.sort.name': 'Name',
  'members.sort.status': 'Status',
  'members.sort.reset': 'Reset Sort',
  'members.sort.resetTitle': 'Reset to default sorting (Name A-Z)',
  'members.count.found': '{count} member{plural} found',
  'members.count.sortedBy': '• Sorted by {field} ({dir})',
  'members.status.active': 'ACTIVE',
  'members.status.inactive': 'INACTIVE',
  'members.detail.slots': 'Slots',
  'members.detail.nationalId': 'National ID',
  'members.fin.totalMonthly': 'Total Monthly Amount:',
  'members.fin.nextReceive': 'Next Receive Month:',
  'members.btn.viewDetails': 'View Details',
  'members.btn.delete': 'Delete Member',
  'members.table.name': 'Name',
  'members.table.status': 'Status',
  'members.table.nationalId': 'National ID',
  'members.table.phone': 'Phone',
  'members.table.city': 'City',
  'members.table.slots': 'Slots',
  'members.table.monthlyAmount': 'Monthly Amount',
  'members.table.nextReceive': 'Next Receive',
  'members.table.actions': 'Actions',
  'members.empty.title': 'No Members Found',
  'members.empty.desc': 'No members match your current search criteria',
  'members.signups.title': 'New Sign-ups',
  'members.signups.count': '{count} sign-up{plural}',
  'members.signups.empty': 'No new sign-ups waiting for review',
  'members.signups.submitted': 'Submitted',
  'members.signups.email': 'Email',
  'members.signups.bank': 'Bank',
  'members.signups.approve': 'Approve',
  'members.signups.reject': 'Reject',
  'members.signups.approveError': 'Could not approve this sign-up. The person may already be a member.',
  'members.signups.detailsTitle': 'Sign-up details',

  // Signup page
  'signup.title': 'Become a member',
  'signup.subtitle': 'Fill in your details. An administrator will review your sign-up.',
  'signup.section.personal': 'Personal Information',
  'signup.section.contact': 'Contact & Identification',
  'signup.section.banking': 'Banking Information',
  'signup.field.firstName': 'First Name',
  'signup.field.middleName': 'Middle Name',
  'signup.field.lastName': 'Last Name',
  'signup.field.birthDate': 'Birth Date',
  'signup.field.birthplace': 'Birthplace',
  'signup.field.address': 'Address',
  'signup.field.city': 'City',
  'signup.field.selectCity': 'Select city',
  'signup.field.nationality': 'Nationality',
  'signup.field.selectNationality': 'Select nationality',
  'signup.field.phone': 'Phone Number',
  'signup.field.email': 'Email',
  'signup.field.nationalId': 'National ID',
  'signup.field.occupation': 'Occupation',
  'signup.field.bankName': 'Bank Name',
  'signup.field.selectBank': 'Select bank',
  'signup.field.accountNumber': 'Account Number',
  'signup.submit': 'Submit sign-up',
  'signup.submitting': 'Submitting...',
  'signup.success.title': 'Sign-up received',
  'signup.success.body': 'Thank you. An administrator will review your details and contact you.',
  'signup.success.back': 'Back to home',
  'signup.error.firstName': 'First name is required',
  'signup.error.lastName': 'Last name is required',
  'signup.error.birthDate': 'Birth date is required',
  'signup.error.birthplace': 'Birthplace is required',
  'signup.error.address': 'Address is required',
  'signup.error.city': 'City is required',
  'signup.error.phone': 'Phone number is required',
  'signup.error.email': 'Email is required',
  'signup.error.emailInvalid': 'Please enter a valid email address',
  'signup.error.nationalId': 'National ID is required',
  'signup.error.nationality': 'Nationality is required',
  'signup.error.occupation': 'Occupation is required',
  'signup.error.bankName': 'Bank name is required',
  'signup.error.accountNumber': 'Account number is required',
  'signup.error.submit': 'Could not submit your sign-up. Please try again.',
  'signup.wizard.progress': 'Sign-up steps',
  'signup.wizard.step': 'Step {current} of {total}',
  'signup.wizard.next': 'Next',
  'signup.wizard.back': 'Back',

  // Payouts page
  'payouts.title': 'Payouts',
  'payouts.loading': 'Loading payouts...',
  'payouts.error.title': 'Error Loading Payouts',
  'payouts.retry': 'Try Again',
  'payouts.subtitle.current': 'Current month ({month}) - Members receiving payouts this month',
  'payouts.subtitle.other': '{month} - Members receiving payouts for this month',
  'payouts.print': 'Print',
  'payouts.privacy.title': 'Privacy Notice',
  'payouts.privacy.body': 'You are viewing only your own payout records. Administrators can see all payout records.',
  'payouts.summary.count.current': 'Current Month Payouts',
  'payouts.summary.count.other': '{month} Payouts',
  'payouts.summary.amount.current': 'Current Month Amount',
  'payouts.summary.amount.other': '{month} Amount',
  'payouts.summary.completed': 'Completed',
  'payouts.summary.pending': 'Pending',
  'payouts.note.showing': 'Showing payouts for {month} - Members whose assigned month is {month}',
  'payouts.filters.toggle': 'Filters',
  'payouts.filters.type': 'Filter Type:',
  'payouts.filters.type.all': 'All Fields',
  'payouts.filters.type.member': 'Member Name',
  'payouts.filters.type.group': 'Group Name',
  'payouts.filters.type.bank': 'Bank Name',
  'payouts.filters.search': 'Search:',
  'payouts.filters.search.placeholder': 'Enter search term...',
  'payouts.filters.status': 'Status:',
  'payouts.filters.status.all': 'All Statuses',
  'payouts.filters.month': 'Month:',
  'payouts.filters.clear': 'Clear Filters',
  'payouts.table.member': 'Member Name',
  'payouts.table.group': 'Group',
  'payouts.table.total': 'Total Amount',
  'payouts.table.status': 'Status',
  'payouts.table.bank': 'Bank',
  'payouts.table.actions': 'Actions',
  'payouts.empty.title': 'No payouts found for {month}',
  'payouts.empty.desc': 'This means no members are assigned to receive payouts for this month',
  'payouts.pagination.showing': 'Showing {from}-{to} of {total} payouts',
  'payouts.pagination.previous': 'Previous',
  'payouts.pagination.next': 'Next',
  'payouts.pagination.show': 'Show:',

  // Payments Due page
  'paymentsDue.title': 'Payments Due',
  'paymentsDue.subtitle.admin': 'All slots from all groups',
  'paymentsDue.subtitle.user': 'Your payment slots',
  'paymentsDue.loading': 'Loading unpaid slots...',
  'paymentsDue.error.retry': 'Retry',
  'paymentsDue.refresh': 'Refresh',
  'paymentsDue.performance': 'Performance',
  'paymentsDue.notice.own': 'Viewing only your records',
  'paymentsDue.notice.filter.paid': '✅ Showing paid slots only',
  'paymentsDue.notice.filter.unpaid': '⚠️ Showing unpaid slots only',
  'paymentsDue.stats.filteredSlots.admin': 'Filtered Slots',
  'paymentsDue.stats.filteredSlots.user': 'Your Filtered Slots',
  'paymentsDue.stats.filteredAmount.admin': 'Filtered Amount',
  'paymentsDue.stats.filteredAmount.user': 'Your Filtered Amount',
  'paymentsDue.stats.totalPaid.admin': 'Total Amount Paid',
  'paymentsDue.stats.totalPaid.user': 'Amount Paid',
  'paymentsDue.stats.totalDue.admin': 'Total Amount Due',
  'paymentsDue.stats.totalDue.user': 'Amount Due',
  'paymentsDue.export.label': 'Export to PDF:',
  'paymentsDue.export.all': 'All Rows',
  'paymentsDue.export.paid': 'Paid Only',
  'paymentsDue.export.unpaid': 'Unpaid Only',
  'paymentsDue.filter.paymentStatus': 'Payment Status:',
  'paymentsDue.filter.all': 'All Slots',
  'paymentsDue.filter.unpaid': 'Unpaid Only',
  'paymentsDue.filter.paid': 'Paid Only',
  'paymentsDue.filter.clear': 'Clear Filters',
  'paymentsDue.pageSize.label': 'Rows per page:',
  'paymentsDue.search.in': 'Search in:',
  'paymentsDue.search.field.all': 'All Fields',
  'paymentsDue.search.field.name': 'Member Name',
  'paymentsDue.search.field.group': 'Group Name',
  'paymentsDue.search.field.amount': 'Amount',
  'paymentsDue.search.placeholder': 'Search payments due...',
  'paymentsDue.none.title': 'No Payments Due',
  'paymentsDue.none.desc': "All members have paid their current month's slots!",
}

const nl: Translations = {
  'nav.dashboard': 'Dashboard',
  'nav.myDashboard': 'Mijn dashboard',
  'nav.settings': 'Instellingen',
  'nav.groups': 'Groepen',
  'nav.members': 'Leden',
  'nav.payments': 'Betalingen',
  'nav.payouts': 'Uitbetalingen',
  'nav.paymentsDue': 'Openstaande betalingen',
  'nav.analytics': 'Analyse',
  'nav.messages': 'Berichten',
  'nav.paymentLogs': 'Betalingslogboeken',
  'nav.userManagement': 'Gebruikersbeheer',
  'nav.loginLogs': 'Inloglogboeken',
  'auth.login': 'Inloggen',
  'auth.signup': 'Aanmelden',
  'settings.pageTitle': 'Instellingen',
  'settings.pageSubtitle': 'Beheer je accountvoorkeuren en app-instellingen',
  'settings.savePreferences': 'Voorkeuren opslaan',
  'settings.editProfile': 'Profiel bewerken',
  'settings.cancel': 'Annuleren',
  'settings.saveChanges': 'Wijzigingen opslaan',
  'settings.tabs.profile': 'Profiel',
  'settings.tabs.notifications': 'Meldingen',
  'settings.tabs.security': 'Beveiliging',
  'settings.tabs.appearance': 'Weergave',
  'settings.tabs.language': 'Taal',
  'settings.tabs.data': 'Gegevens & Export',
  'settings.tabs.banks': 'Banken',
  'settings.tabs.performance': 'Prestaties',
  'appearance.title': 'Weergave-instellingen',
  'appearance.theme': 'Thema',
  'appearance.choose': 'Kies je voorkeur voor het kleurenschema',
  'language.title': 'Taalinstellingen',
  'language.choose': 'Kies je voorkeurstaal voor de applicatie',
  'language.english': 'Engels',
  'language.dutch': 'Nederlands',
  'footer.rights': 'Alle rechten voorbehouden',
  'footer.email': 'E-mail',
  'dashboard.title': 'Dashboard',
  'dashboard.subtitle': 'Overzicht van je Kasmoni-groepen en betalingen',
  'dashboard.addPayment': 'Betaling toevoegen',
  'dashboard.createGroup': 'Groep aanmaken',
  'dashboard.welcome': 'Welkom bij Sranan Kasmoni',
  'dashboard.getStarted': 'Je dashboard is klaar maar er zijn nog geen gegevens. Ga aan de slag door:',
  'dashboard.createYourFirstGroup': 'Maak je eerste groep aan',
  'dashboard.addYourFirstPayment': 'Voeg je eerste betaling toe',
  'dashboard.noActiveGroups': 'Geen actieve groepen',
  'dashboard.recentActivity': 'Recente activiteit',
  'dashboard.recentPayments': 'Recente betalingen',
  'dashboard.recentMembers': 'Recente leden',
  'dashboard.recentGroups': 'Recente groepen',
  'dashboard.noRecentPayments': 'Geen recente betalingen',
  'dashboard.noRecentMembers': 'Geen recente leden',
  'dashboard.noRecentGroups': 'Geen recente groepen',
  'dashboard.stats.totalExpected': 'Totaal verwacht bedrag',
  'dashboard.stats.totalPaid': 'Totaal betaald bedrag',
  'dashboard.stats.totalReceived': 'Totaal ontvangen bedrag',
  'dashboard.stats.pendingPayments': 'Openstaande betalingen',
  'dashboard.stats.totalDue': 'Totaal verschuldigd bedrag',
  'dashboard.stats.overduePayments': 'Achterstallige betalingen',
  'dashboard.stats.totalPayouts': 'Totale uitbetalingen',
  'dashboard.stats.activeGroups': 'Actieve groepen',
  'dashboard.stats.activeMembers': 'Actieve leden',
  'dashboard.groups.all': 'Alle groepen',
  'dashboard.groups.headers.name': 'Groepsnaam',
  'dashboard.groups.headers.monthlyAmount': 'Maandelijks bedrag',
  'dashboard.groups.headers.nextRecipient': 'Volgende ontvanger',
  'dashboard.groups.headers.slots': 'Slots',
  'dashboard.groups.headers.slotsProgress': 'Slots-voortgang',
  'dashboard.groups.headers.last': 'Laatste',
  'dashboard.groups.headers.created': 'Aangemaakt',
  'common.refreshingData': 'Gegevens verversen...',
  'common.tryAgain': 'Opnieuw proberen',
  'common.testDatabase': 'Database testen',
  'common.loading': 'Bezig met laden...',
  'common.viewDetails': 'Details bekijken',
  'common.cards': 'Kaarten',
  'common.table': 'Tabel',
  'groups.title': 'Groepen',
  'groups.manageSubtitle': 'Beheer je spaargroepen',
  'groups.viewSubtitle': 'Bekijk je spaargroepen',
  'groups.downloadSample': 'Voorbeeld-CSV downloaden',
  'groups.exportGroups': 'Groepen exporteren',
  'groups.importCsv': 'CSV importeren',
  'groups.createNew': 'Nieuwe groep aanmaken',
  'groups.loading': 'Groepen laden...',
  'groups.noGroupsTitle': 'Nog geen groepen',
  'groups.noGroupsAdmin': 'Maak je eerste spaargroep aan om te beginnen',
  'groups.noGroupsUser': 'Er zijn nog geen groepen beschikbaar',
  'groups.activeSection': 'Actieve groepen',
  'groups.upcomingSection': 'Aankomende groepen',
  'groups.closedSection': 'Gesloten groepen',
  'groups.sectionCountOne': '{count} groep',
  'groups.sectionCountMany': '{count} groepen',
  'groups.exportPdf': 'PDF exporteren',
  'groups.exportingPdf': 'Exporteren...',
  'groups.exportPdfError': 'PDF exporteren mislukt. Probeer het opnieuw.',
  'myDashboard.title': 'Mijn dashboard',
  'myDashboard.subtitle': 'Welkom terug, {name}! Hier is je persoonlijk overzicht',
  'myDashboard.refreshing': 'Verversen...',
  'myDashboard.refreshData': 'Gegevens verversen',
  'myDashboard.slotsOverview': 'Overzicht van mijn slots',
  'myDashboard.noSlotsTitle': 'Geen slots gevonden',
  'myDashboard.noSlotsDesc': 'Je hebt nog geen toegewezen slots. Neem contact op met je groepsbeheerder om te beginnen.',
  'myDashboard.recentActivity': 'Recente activiteit',

  // Landing page
  'landing.hero.titleLine1': 'Kasmoni',
  'landing.hero.titleLine2': 'Bouw vermogen. Bouw vertrouwen. Samen.',
  'landing.hero.subtitle': 'Sluit je aan bij het vertrouwde spaarplatform dat mensen samenbrengt om financiële doelen te bereiken met wederzijdse steun en transparantie.',
  'landing.hero.getStarted': 'Begin vandaag',
  'landing.hero.exploreGroups': 'Groepen verkennen',
  'landing.stats.activeGroups': 'Actieve groepen',
  'landing.stats.communityMembers': 'Communityleden',
  'landing.stats.totalSavings': 'Totale besparingen',
  'landing.stats.roundsCompleted': 'Rondes voltooid',
  'landing.how.title': 'Hoe werkt Kasmoni',
  'landing.how.subtitle': 'Een eenvoudig en transparant systeem waarmee communities samen kunnen sparen',
  'landing.how.step1.title': 'Word lid van een groep',
  'landing.how.step1.desc': 'Zoek een spaar-groep die past bij je schema en bijdrage, vanaf SRD 1.000.',
  'landing.how.step2.title': 'Spaar regelmatig',
  'landing.how.step2.desc': 'Doe je maandelijkse bijdragen op tijd. Iedereen draagt elke maand hetzelfde bedrag bij.',
  'landing.how.step3.title': 'Ontvang jouw beurt',
  'landing.how.step3.desc': 'Wanneer jij aan de beurt bent, ontvang je de volledige pot – alle bijdragen van je groepsleden.',
  'landing.how.step4.title': 'Bouw vertrouwen op',
  'landing.how.step4.desc': 'Blijf sparen en anderen ondersteunen en bouw duurzame relaties en financiële zekerheid op.',
  'landing.why.title': 'Waarom kiezen voor Sranan Kasmoni?',
  'landing.why.item1.title': 'Geen banken, geen BKR',
  'landing.why.item1.desc': 'Gewoon echte mensen die echte mensen helpen met transparant, community-gedreven sparen.',
  'landing.why.item2.title': 'Veilig & transparant',
  'landing.why.item2.desc': 'Elke transactie wordt vastgelegd en is zichtbaar voor alle groepsleden voor volledige transparantie.',
  'landing.why.item3.title': 'Flexibel & toegankelijk',
  'landing.why.item3.desc': 'Kies je bijdrage en sluit je aan bij groepen die bij je situatie passen.',
  'landing.why.item4.title': 'Community support',
  'landing.why.item4.desc': 'Bouw duurzame relaties terwijl je samen je financiële doelen bereikt.',
  'landing.cta.title': 'Klaar om je financiële reis te starten?',
  'landing.cta.subtitle': 'Sluit je aan bij duizenden Surinamers die samen vermogen en vertrouwen opbouwen.',
  'landing.cta.primary': 'Vandaag beginnen met sparen',
  'landing.cta.secondary': 'Groepen bekijken',
  'landing.contact.title': 'Neem contact op',
  'landing.contact.email': 'E-mail',
  'landing.contact.followUs': 'Volg ons',
  'landing.contact.facebook': 'Facebook',
  'landing.contact.twitter': 'Twitter',
  'landing.contact.message': 'Vragen over deelname aan een Kasmoni-groep? Ons team helpt je graag op weg met community-sparen.',

  // Payments page
  'payments.title': 'Betalingen',
  'payments.subtitle.admin': 'Volg alle betalingen en hun status',
  'payments.subtitle.user': 'Volg je eigen betalingen en hun status',
  'payments.userNotice': 'Alleen je eigen betaalrecords worden getoond',
  'payments.recordPayment': 'Betaling registreren',
  'payments.summary.totalPaid': 'Totaal Betaald',
  'payments.summary.received': 'Ontvangen',
  'payments.summary.pending': 'In afwachting',
  'payments.summary.notPaid': 'Niet betaald',
  'payments.summary.settled': 'Afgewikkeld',
  'payments.summary.count': '{count} betalingen',
  'payments.pagination.rowsPerPage': 'Rijen per pagina:',
  'payments.pagination.showing': 'Toont {from}-{to} van {total} betalingen',
  'payments.pagination.pageOf': 'Pagina {page} van {pages}',
  'payments.loading': 'Betalingen laden...',
  'payments.section.all': 'Alle betalingen',
  'payments.section.yours': 'Jouw betalingen',
  'payments.privacy.title': 'Privacy melding:',
  'payments.privacy.body': 'Je bekijkt alleen je eigen betaalrecords. Beheerders kunnen alle betalingen in het systeem zien.',
  'payments.empty.title': 'Geen betalingen gevonden',
  'payments.empty.desc.admin': 'Geen betalingen komen overeen met je filters. Pas je zoekcriteria aan of registreer je eerste betaling.',
  'payments.empty.desc.user': 'Je hebt nog geen betalingen.',

  // Members page
  'members.title': 'Leden',
  'members.subtitle.admin': 'Beheer de leden van je organisatie',
  'members.subtitle.user': 'Bekijk je ledendata',
  'members.loading': 'Leden laden...',
  'members.downloadSample': 'Voorbeeld-CSV downloaden',
  'members.importCsv': 'CSV importeren',
  'members.addMember': 'Lid toevoegen',
  'members.viewMode': 'Weergave:',
  'members.cards': 'Kaarten',
  'members.table': 'Tabel',
  'members.csvResults': 'CSV-importresultaten',
  'members.importErrors': 'Imporfouten:',
  'members.searchPlaceholder': 'Zoek leden op naam, ID, telefoon, bank of rekeningnummer...',
  'members.filter.allCities': 'Alle steden',
  'members.sort.by': 'Sorteren op:',
  'members.sort.name': 'Naam',
  'members.sort.status': 'Status',
  'members.sort.reset': 'Sortering resetten',
  'members.sort.resetTitle': 'Terug naar standaard sortering (Naam A-Z)',
  'members.count.found': '{count} lid{plural} gevonden',
  'members.count.sortedBy': '• Gesorteerd op {field} ({dir})',
  'members.status.active': 'ACTIEF',
  'members.status.inactive': 'INACTIEF',
  'members.detail.slots': 'Slots',
  'members.detail.nationalId': 'Identiteitsnummer',
  'members.fin.totalMonthly': 'Totaal maandelijks bedrag:',
  'members.fin.nextReceive': 'Volgende ontvangstdatum:',
  'members.btn.viewDetails': 'Details bekijken',
  'members.btn.delete': 'Lid verwijderen',
  'members.table.name': 'Naam',
  'members.table.status': 'Status',
  'members.table.nationalId': 'Identiteitsnummer',
  'members.table.phone': 'Telefoon',
  'members.table.city': 'Stad',
  'members.table.slots': 'Slots',
  'members.table.monthlyAmount': 'Maandelijks bedrag',
  'members.table.nextReceive': 'Volgende ontvangst',
  'members.table.actions': 'Acties',
  'members.empty.title': 'Geen leden gevonden',
  'members.empty.desc': 'Geen leden komen overeen met je huidige zoekcriteria',
  'members.signups.title': 'Nieuwe aanmeldingen',
  'members.signups.count': '{count} aanmelding{plural}',
  'members.signups.empty': 'Geen nieuwe aanmeldingen ter beoordeling',
  'members.signups.submitted': 'Ingediend',
  'members.signups.email': 'E-mail',
  'members.signups.bank': 'Bank',
  'members.signups.approve': 'Goedkeuren',
  'members.signups.reject': 'Afwijzen',
  'members.signups.approveError': 'Deze aanmelding kon niet worden goedgekeurd. Deze persoon is mogelijk al lid.',
  'members.signups.detailsTitle': 'Aanmelddetails',

  // Signup page
  'signup.title': 'Word lid',
  'signup.subtitle': 'Vul je gegevens in. Een beheerder beoordeelt je aanmelding.',
  'signup.section.personal': 'Persoonlijke gegevens',
  'signup.section.contact': 'Contact & identificatie',
  'signup.section.banking': 'Bankgegevens',
  'signup.field.firstName': 'Voornaam',
  'signup.field.middleName': 'Tweede naam',
  'signup.field.lastName': 'Achternaam',
  'signup.field.birthDate': 'Geboortedatum',
  'signup.field.birthplace': 'Geboorteplaats',
  'signup.field.address': 'Adres',
  'signup.field.city': 'Stad',
  'signup.field.selectCity': 'Selecteer stad',
  'signup.field.nationality': 'Nationaliteit',
  'signup.field.selectNationality': 'Selecteer nationaliteit',
  'signup.field.phone': 'Telefoonnummer',
  'signup.field.email': 'E-mail',
  'signup.field.nationalId': 'Identiteitsnummer',
  'signup.field.occupation': 'Beroep',
  'signup.field.bankName': 'Banknaam',
  'signup.field.selectBank': 'Selecteer bank',
  'signup.field.accountNumber': 'Rekeningnummer',
  'signup.submit': 'Aanmelding versturen',
  'signup.submitting': 'Versturen...',
  'signup.success.title': 'Aanmelding ontvangen',
  'signup.success.body': 'Dank je. Een beheerder beoordeelt je gegevens en neemt contact met je op.',
  'signup.success.back': 'Terug naar home',
  'signup.error.firstName': 'Voornaam is verplicht',
  'signup.error.lastName': 'Achternaam is verplicht',
  'signup.error.birthDate': 'Geboortedatum is verplicht',
  'signup.error.birthplace': 'Geboorteplaats is verplicht',
  'signup.error.address': 'Adres is verplicht',
  'signup.error.city': 'Stad is verplicht',
  'signup.error.phone': 'Telefoonnummer is verplicht',
  'signup.error.email': 'E-mail is verplicht',
  'signup.error.emailInvalid': 'Voer een geldig e-mailadres in',
  'signup.error.nationalId': 'Identiteitsnummer is verplicht',
  'signup.error.nationality': 'Nationaliteit is verplicht',
  'signup.error.occupation': 'Beroep is verplicht',
  'signup.error.bankName': 'Banknaam is verplicht',
  'signup.error.accountNumber': 'Rekeningnummer is verplicht',
  'signup.error.submit': 'Je aanmelding kon niet worden verstuurd. Probeer het opnieuw.',
  'signup.wizard.progress': 'Aanmeldstappen',
  'signup.wizard.step': 'Stap {current} van {total}',
  'signup.wizard.next': 'Volgende',
  'signup.wizard.back': 'Terug',

  // Payouts page
  'payouts.title': 'Uitbetalingen',
  'payouts.loading': 'Uitbetalingen laden...',
  'payouts.error.title': 'Fout bij laden van uitbetalingen',
  'payouts.retry': 'Opnieuw proberen',
  'payouts.subtitle.current': 'Huidige maand ({month}) - Leden die deze maand uitbetaald worden',
  'payouts.subtitle.other': '{month} - Leden die deze maand uitbetaald worden',
  'payouts.print': 'Afdrukken',
  'payouts.privacy.title': 'Privacy melding',
  'payouts.privacy.body': 'Je bekijkt alleen je eigen uitbetalingen. Beheerders kunnen alle uitbetalingen zien.',
  'payouts.summary.count.current': 'Uitbetalingen deze maand',
  'payouts.summary.count.other': '{month} uitbetalingen',
  'payouts.summary.amount.current': 'Bedrag deze maand',
  'payouts.summary.amount.other': '{month} bedrag',
  'payouts.summary.completed': 'Voltooid',
  'payouts.summary.pending': 'In afwachting',
  'payouts.note.showing': 'Toont uitbetalingen voor {month} - Leden met de toegewezen maand {month}',
  'payouts.filters.toggle': 'Filters',
  'payouts.filters.type': 'Filtertype:',
  'payouts.filters.type.all': 'Alle velden',
  'payouts.filters.type.member': 'Lidnaam',
  'payouts.filters.type.group': 'Groepsnaam',
  'payouts.filters.type.bank': 'Banknaam',
  'payouts.filters.search': 'Zoeken:',
  'payouts.filters.search.placeholder': 'Voer zoekterm in...',
  'payouts.filters.status': 'Status:',
  'payouts.filters.status.all': 'Alle statussen',
  'payouts.filters.month': 'Maand:',
  'payouts.filters.clear': 'Filters wissen',
  'payouts.table.member': 'Lidnaam',
  'payouts.table.group': 'Groep',
  'payouts.table.total': 'Totaalbedrag',
  'payouts.table.status': 'Status',
  'payouts.table.bank': 'Bank',
  'payouts.table.actions': 'Acties',
  'payouts.empty.title': 'Geen uitbetalingen gevonden voor {month}',
  'payouts.empty.desc': 'Dit betekent dat er geen leden zijn toegewezen voor uitbetaling deze maand',
  'payouts.pagination.showing': 'Toont {from}-{to} van {total} uitbetalingen',
  'payouts.pagination.previous': 'Vorige',
  'payouts.pagination.next': 'Volgende',
  'payouts.pagination.show': 'Toon:',

  // Payments Due page
  'paymentsDue.title': 'Openstaande betalingen',
  'paymentsDue.subtitle.admin': 'Alle slots van alle groepen',
  'paymentsDue.subtitle.user': 'Jouw betalingsslots',
  'paymentsDue.loading': 'Openstaande slots laden...',
  'paymentsDue.error.retry': 'Opnieuw proberen',
  'paymentsDue.refresh': 'Verversen',
  'paymentsDue.performance': 'Prestaties',
  'paymentsDue.notice.own': 'Alleen je eigen records worden getoond',
  'paymentsDue.notice.filter.paid': '✅ Alleen betaalde slots',
  'paymentsDue.notice.filter.unpaid': '⚠️ Alleen onbetaalde slots',
  'paymentsDue.stats.filteredSlots.admin': 'Gefilterde slots',
  'paymentsDue.stats.filteredSlots.user': 'Jouw gefilterde slots',
  'paymentsDue.stats.filteredAmount.admin': 'Gefilterd bedrag',
  'paymentsDue.stats.filteredAmount.user': 'Jouw gefilterd bedrag',
  'paymentsDue.stats.totalPaid.admin': 'Totaal betaald bedrag',
  'paymentsDue.stats.totalPaid.user': 'Betaald bedrag',
  'paymentsDue.stats.totalDue.admin': 'Totaal verschuldigd bedrag',
  'paymentsDue.stats.totalDue.user': 'Verschuldigd bedrag',
  'paymentsDue.export.label': 'Exporteren naar PDF:',
  'paymentsDue.export.all': 'Alle rijen',
  'paymentsDue.export.paid': 'Alleen betaald',
  'paymentsDue.export.unpaid': 'Alleen onbetaald',
  'paymentsDue.filter.paymentStatus': 'Betaalstatus:',
  'paymentsDue.filter.all': 'Alle slots',
  'paymentsDue.filter.unpaid': 'Alleen onbetaald',
  'paymentsDue.filter.paid': 'Alleen betaald',
  'paymentsDue.filter.clear': 'Filters wissen',
  'paymentsDue.pageSize.label': 'Rijen per pagina:',
  'paymentsDue.search.in': 'Zoeken in:',
  'paymentsDue.search.field.all': 'Alle velden',
  'paymentsDue.search.field.name': 'Lidnaam',
  'paymentsDue.search.field.group': 'Groepsnaam',
  'paymentsDue.search.field.amount': 'Bedrag',
  'paymentsDue.search.placeholder': 'Zoek openstaande betalingen...',
  'paymentsDue.none.title': 'Geen openstaande betalingen',
  'paymentsDue.none.desc': 'Alle leden hebben hun slots voor deze maand betaald!'
}

const LOCALE_STORAGE_KEY = 'locale'

interface LanguageContextValue {
  locale: SupportedLocale
  setLocale: (locale: SupportedLocale) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

export const useLanguage = (): LanguageContextValue => {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [locale, setLocaleState] = useState<SupportedLocale>('en')

  useEffect(() => {
    const stored = localStorage.getItem(LOCALE_STORAGE_KEY) as SupportedLocale | null
    if (stored === 'en' || stored === 'nl') {
      setLocaleState(stored)
    }
  }, [])

  const setLocale = (next: SupportedLocale) => {
    setLocaleState(next)
    localStorage.setItem(LOCALE_STORAGE_KEY, next)
    document.documentElement.setAttribute('lang', next)
  }

  const dictionaries: Record<SupportedLocale, Translations> = useMemo(() => ({ en, nl }), [])

  const t = (key: string): string => {
    const dict = dictionaries[locale] || en
    return dict[key] ?? key
  }

  const value = useMemo<LanguageContextValue>(() => ({ locale, setLocale, t }), [locale])

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}


